### ISSUE TITLE
Have an "run until steady-state" option

### ISSUE THREAD

**Issue by AleMorales** [JuliaDiffEq/SteadyStateDiffEq.jl#5]
In the past I have used the DESolve suite from R and I always liked the idea that one could calculate the steady-state by simply running the simulation until the state variables did not change more than an specified tolerance. This always worked even when non-linear solver got stuck. Furthermore, this may be useful for models where the steady-state is dependent on the initial conditions (i.e. hysteresis).

I wonder if such a feature could be added to this package (or somewhere else in the suite) and what the best strategy would be. Maybe a new problem type is required?

**Comment by ChrisRackauckas** [comment]
Yes. I would do this in two steps. The real work would be just to create a `DiscreteCallback` (say called `SteadyStateTerminate`) that terminates when steady state is reached. That would do the heavy lifting. I would suggest putting it in the CallbackLibrary too since it is useful on its own. Then I would create a convenience algorithm here `DynamicSS(alg)` that takes the steady-state problem and solves for the steady-state using the given `alg` with the callback.

**Comment by ChrisRackauckas** [comment]
Cross reference: https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/228
